"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var fs = require("file-system");
var Imdb_1 = require("./Imdb");
var movie_1 = require("./movie");
var professional_1 = require("./professional");
var professional1 = new professional_1.Professional("Brendan Fraser", 54, 80, 1.91, false, "American", 3, "Actor");
var professional2 = new professional_1.Professional("Nicole Kidman", 56, 60, 1.80, false, "Australian", 0, "Actress");
var professional3 = new professional_1.Professional("Maryl Streep", 74, 58, 1.70, false, "American", 3, "Actress");
var professional4 = new professional_1.Professional("Christopher Nolan", 53, 85, 1.80, false, "English", 0, "Film director");
var professional5 = new professional_1.Professional("Tim Burton", 65, 90, 1.86, false, "American", 0, "Film director");
var professional6 = new professional_1.Professional("Bruce Willis", 68, 95, 1.83, true, "American", 0, "Actor");
var movie1 = new movie_1.Movie("Mamma Mia", 2008, "American", "Musical");
movie1.addActors(professional3);
movie1.addActors(professional1);
movie1.addDirector(professional4);
movie1.addWriter(professional4);
movie1.addLanguage("English");
movie1.addPlatform("Netflix");
movie1.addIsMCU(true);
movie1.addMainCharacterName("Donna");
movie1.addProducer("Movies.SL");
movie1.addDistributor("Universal");
var movie2 = new movie_1.Movie("Moulin Rouge", 2001, "American", "Musical");
movie2.addActors(professional2);
movie2.addDirector(professional5);
movie2.addWriter(professional4);
movie2.addLanguage("English");
movie2.addPlatform("Amazon Prime");
movie2.addIsMCU(false);
movie2.addProducer("20th Century Studios");
movie2.addDistributor("20th Century Studios");
var cine = new Imdb_1.Imdb([movie1, movie2]);
console.log(cine);
// Paso 6: lectura/escritura en fichero. 
// 1. Convertir a un string el objeto Imdb
var dataBaseString = JSON.stringify(cine);
var fileName = "./cine.json";
fs.writeFileSync(fileName, dataBaseString, { encoding: "utf8", mode: 438, flag: "w+" });
